pipeline {
    agent any

    environment {
        IMAGE_NAME = "gcr.io/rama17-05-2020/python-k8s-demo"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ichbinuus/jenkins-repo.git'
            }
        }

       stage('Build Docker Image') {
    steps {
        sh "docker build -t ${FULL_IMAGE} python-k8s-demo/"
    }
}


        stage('Push to GCR') {
            steps {
                withCredentials([file(credentialsId: '73d05379-38c1-4f02-b431-736c922e71d6', variable: 'GCP_KEY')]) {
                    sh '''
                        gcloud auth activate-service-account --key-file=$GCP_KEY
                        gcloud auth configure-docker -q
                        docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}
