pipeline {
    agent any

    environment {
    IMAGE_NAME = "asia-south1-docker.pkg.dev/rama17-05-2020/python-k8s-demo/python-k8s-demo"
    FULL_IMAGE = "${IMAGE_NAME}:${BUILD_NUMBER}"
}


    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ichbinuus/jenkins-repo.git'
            }
        }

       stage('Build Docker Image') {
    steps {
        sh "docker build -t ${FULL_IMAGE} python-k8s-demo/"
    }
}



        stage('Push to GCR') {
            steps {
                withCredentials([file(credentialsId: 'd3b3f50e-b703-44cf-9890-1863036ce38', variable: 'GCP_KEY')]) {
                    sh '''
                        gcloud auth activate-service-account --key-file=$GCP_KEY
                          gcloud auth configure-docker asia-south1-docker.pkg.dev -q
                        docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                    '''
                }
            }
        }
    }
}
