pipeline {
    agent any

    environment {
        PROJECT_ID = 'rama17-05-2020'
        IMAGE_NAME = "gcr.io/${PROJECT_ID}/python-k8s-demo"
        TAG = "${BUILD_NUMBER}"
        FULL_IMAGE = "${IMAGE_NAME}:${TAG}"
        CLUSTER = 'cluster-1'
        REGION = 'asia-south1'
    }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${FULL_IMAGE} ."
            }
        }

        stage('Push to GCR') {
            steps {
                withCredentials([file(credentialsId: '73d05379-38c1-4f02-b431-736c922e71d6', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh 'gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS'
                    sh 'gcloud config set project ${PROJECT_ID}'
                    sh 'gcloud auth configure-docker'
                    sh "docker push ${FULL_IMAGE}"
                }
            }
        }

        stage('Deploy to GKE') {
            steps {
                withCredentials([file(credentialsId: '73d05379-38c1-4f02-b431-736c922e71d6', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh 'gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS'
                    sh "gcloud container clusters get-credentials ${CLUSTER} --region ${REGION}"
                    sh "kubectl set image deployment/python-k8s-deployment python-k8s=${FULL_IMAGE}"
                }
            }
        }
    }
}
