apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-k8s
  template:
    metadata:
      labels:
        app: python-k8s
    spec:
      containers:
      - name: python-k8s
        image: gcr.io/YOUR_PROJECT_ID/python-k8s-demo
        ports:
        - containerPort: 5000