apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-k8s
  template:
    metadata:
      labels:
        app: python-k8s
    spec:
      containers:
      - name: python-k8s
        image: asia-south1-docker.pkg.dev/rama17-05-2020/python-k8s-demo/python-k8s-demo:10
        ports:
        - containerPort: 5000
